language: vim


before_script: |
    git clone https://github.com/junegunn/vader.vim.git

    hg clone https://code.google.com/p/vim/
    cd vim
    ./configure --with-features=huge
    make
    sudo make install
    cd -

script: |
    vim -Nu <(cat << VIMRC
    filetype off
    set rtp+=vader.vim
    set rtp+=.
    filetype plugin indent on
    syntax enable
    VIMRC) -c 'Vader! tests/*' > /dev/null
