language: vim


before_script: |
git clone https://github.com/junegunn/vader.vim.git

script: |
vim -Nu <(cat << VIMRC
filetype off
set rtp+=crunch
set rtp+=.
filetype plugin indent on
syntax enable
VIMRC) -c 'Vader! tests/*' > /dev/null
